version: "3.8"

services:
  # db:
  #   image: postgres:15
  #   restart: always
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_USER=postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/library
    ports:
      - "8000:8000"
    # depends_on:
    #   - db